# Generated by Django 3.0 on 2020-01-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('anchor', models.CharField(max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CodeSnippet', to='blogentry.BlogEntry')),
            ],
        ),
    ]
