# Generated by Django 3.0 on 2020-01-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogentry', '0002_blogcodesnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcodesnippet',
            old_name='code',
            new_name='CodeSnippet',
        ),
    ]
