# Generated by Django 3.0 on 2020-01-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogentry', '0004_blogcodesnippet_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcodesnippet',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
